routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Models\Feature;

Route::get('/', 'HomeController@index');
Route::get('/import', 'HomeController@import');
Route::post('/import', 'HomeController@importExcel');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/features/add-value', function () {
	return View('features._add-value',['id' => $_GET['id']]);
});

Route::get('/features/get-values', function () {
	$feature = Feature::find($_GET['id']);
	return View('features._get-values',['feature' => $feature]);
});
Route::get('/varities/exporData', 'VarityController@check_db');
Route::get('/varities/searchHome', 'VarityController@searchHome');
Route::get('/varities/searchHomeCrossing', 'VarityController@searchHomeCrossing');
Route::get('/varities/addValues', 'VarityController@addValues');
Route::get('/varities/addFeature', 'VarityController@addFeature');
Route::get('/blocks/addFeature', 'BlockController@addFeature');
Route::post('/varities/saveCharacteristics', 'VarityController@saveCharacteristics');
Route::post('/varities/uploadPhoto', 'VarityController@uploadPhoto');
Route::get('/varities/ancesters/{id}/{maxlevel}/{level}', 'VarityController@ancesters');
Route::put('/varities/financial/{varity}', 'VarityController@financialInfo')->name('varities.financialInfo');
Route::resource('varities', 'VarityController');


Route::get('/crossings/zonashow/{id?}', 'CrossingController@zonashow')->name('crossings.zonashow');
Route::get('/crossings/zonaedit/{id?}', 'CrossingController@zonaedit')->name('crossings.zonaedit');
Route::get('/crossings/zonacreate/{id?}', 'CrossingController@zonacreate')->name('crossings.zonacreate');
Route::post('/crossings/zonacreate', 'CrossingController@zonastore')->name('crossings.zonacreate');
Route::get('/crossings/mapout', 'CrossingController@mapout');
Route::get('/crossings/zona', 'CrossingController@zona');
Route::get('/crossings/saveObservations', 'CrossingController@saveObservations');
Route::post('/crossings/uploadPhoto', 'CrossingController@uploadPhoto');
Route::get('/crossings/deleteCodify', 'CrossingController@deleteCodify');
Route::get('/crossings/generateCodify', 'CrossingController@generateCodify');
Route::get('/crossings/codify/{id}', 'CrossingController@codify');
Route::get('/crossings/finishCodify/{id}', 'CrossingController@finishCodify');
Route::get('/crossings/codedJSON/', 'CrossingController@codedJSON');
Route::get('/crossings/items/', 'CrossingController@items');
Route::post('/crossings/saveCodify/', 'CrossingController@saveCodify');
Route::post('/crossings/saveCharacteristics', 'CrossingController@saveCharacteristics');
Route::get('/crossings/check_ancester/', 'CrossingController@check_ancester');


Route::post('/blocks/saveShowFarms','BlockController@saveShowFarms');
Route::get('/blocks/modCaracteristicas','BlockController@modCaracteristicas');
Route::get('/blocks/saveObservation','BlockController@saveObservation');
Route::get('/blocks/getCaracteristicas','BlockController@getCaracteristicas');	
Route::get('/blocks/getFotos','BlockController@getFotos');
Route::get('/blocks/codify','BlockController@codify');
Route::get('/blocks/print','BlockController@print');
Route::get('/blocks/move_position','BlockController@move_position');
Route::get('/blocks/info_to_compare','BlockController@info_to_compare');
Route::get('/blocks/deleteCodify/{id}','BlockController@deleteCodify');
Route::get('/blocks/getDataChar/','BlockController@getDataChar');
Route::get('/blocks/reorder/{id}','BlockController@reorder');
Route::get('/blocks/discard/','BlockController@discard');
Route::get('/blocks/review/','BlockController@review');
Route::get('/blocks/export/{id}','BlockController@export');
Route::get('/blocks/send_to_blocks','BlockController@send_to_blocks');
Route::get('/blocks/trash','BlockController@trash');
Route::get('/blocks/show_trash/{id}','BlockController@show_trash');
Route::get('/blocks/mark_offline/','BlockController@mark_offline');
Route::resource('blocks', 'BlockController');

Route::get('/mapouts/generateCodify/{id}','MapoutController@generateCodify');
Route::get('/mapouts/deleteCodify/{id}','MapoutController@deleteCodify');
Route::post('/mapouts/updatePosition', 'MapoutController@updatePosition')->name('mapouts.updatePosition');
Route::post('/mapouts/addPositions', 'MapoutController@addPositions')->name('mapouts.addPositions');
Route::resource('mapouts', 'MapoutController');
Route::resource('crossings', 'CrossingController');
Route::resource('features', 'FeatureController');

Route::get("farmers/provinces/", "FarmersController@getProvinces");
Route::get("farmers/communities/", "FarmersController@getCommunities");
Route::get("farmers/lands/", "FarmersController@getLands");

Route::resource('farmers', 'FarmersController');
Route::resource('companies', 'CompanyController');
Route::resource('lands', 'LandController');
Route::resource('traceability', 'TraceabilityController');
Route::get("royalties/create/{farmer_id}", "RoyaltiesController@create");

Route::resource('royalties', 'RoyaltiesController');

Route::get('/results/getData/','ResultsController@getData');
Route::get('/results/crossings/','ResultsController@crossings');
Route::get('/results/fries/','ResultsController@fries');
Route::get('/results/searchCrossings/','CrossingController@searchCrossings');
Route::get('/results/getVaritiesFromBlock/','ResultsController@getVaritiesFromBlock');
Route::get('/results/getChildrensFromVarity/','ResultsController@getChildrensFromVarity');
Route::get('/results/getCaracteristicas/','ResultsController@getCaracteristicas');
Route::get('/results/modCaracteristicas','ResultsController@modCaracteristicas');
Route::any('/fries/save/','BlockController@saveDataFries');			
Route::get('/fries/getData/','BlockController@getDataFries');
Route::any('/fries/updateFries/','BlockController@updateDataFries');			

Route::get('/results/preview_report/','ResultsController@preview_report');
Route::get('/results/load_preview/','ResultsController@load_preview');
Route::any('/results/report/','ResultsController@report');
Route::get('/results/getVarities/','ResultsController@varities');
Route::get('/results/info_to_compare/','ResultsController@info_to_compare');
Route::get('/results/getBlocksByYear/','ResultsController@getBlocksByYear');
Route::get('/results/getVarityByname/','ResultsController@getVarityByname');
Route::get('/results/getVarityBynameInfo/','ResultsController@getVarityBynameInfo');
Route::get('/results/getDataFeature/','ResultsController@getDataFeature');
Route::get('/results/stadistics/','ResultsController@stadistics');

Route::resource('results', 'ResultsController');

Route::resource('std_market', 'StdMarketController');


Route::DELETE('/greenhouse/destroy_greenhouse', 'GreenHouseController@destroy_greenhouse')->name('greenhouse.destroy_greenhouse');
Route::PATCH('/greenhouse/update_greenhouse', 'GreenHouseController@update_greenhouse')->name('greenhouse.update_greenhouse');
Route::get('/greenhouse/asociate_crossing/{id}','GreenHouseController@asociate_crossing')->name('greenhouse.asociate_crossing');
Route::get('/greenhouse/crossings_add/','GreenHouseController@crossings_add');
Route::get('/greenhouse/crossings_added/{id}','GreenHouseController@crossings_added');
Route::post('/greenhouse/store_crossings', 'GreenHouseController@store_crossings');
Route::post('/greenhouse/delete_crossings', 'GreenHouseController@delete_crossings');


Route::get('/greenhouse/generateCodify/{id}','GreenHouseController@generateCodify');
Route::get('/greenhouse/show_mobile/{id}','GreenHouseController@show_mobile');
Route::get('/greenhouse/crossings_ok/{id}','GreenHouseController@crossings_ok');
Route::get('/greenhouse/crossings_list/{id}','GreenHouseController@crossings_list');
Route::get('/greenhouse/show_mobile/{id}','GreenHouseController@show_mobile');
Route::get('/public/draw_greenhouse/{id}','GreenHouseController@draw_greenhouse');
Route::get('draw_greenhouse/{id}','GreenHouseController@draw_greenhouse');
Route::get('/greenhouse/deleteCodify/{id}','GreenHouseController@deleteCodify');
Route::post('/greenhouse/updatePosition', 'GreenHouseController@updatePosition')->name('greenhouse.updatePosition');
Route::post('/greenhouse/addPositions', 'GreenHouseController@addPositions')->name('greenhouse.addPositions');
Route::get('/greenhouse/switch/{varity_id}/{father_id}/{mother_id}','GreenHouseController@switchFathers');
Route::get('/greenhouse/polen/{father_id}/{mother_id}/{status}','GreenHouseController@savePolen');
Route::get('/greenhouse/berries/{id}/{nro_berries}','GreenHouseController@save_berries');
Route::get('/greenhouse/glasses/{id}/{nro_glases}','GreenHouseController@save_glasses');
Route::get('/greenhouse/get_data_chart','GreenHouseController@get_data_chart');
Route::resource('greenhouse', 'GreenHouseController');

Route::get('/relative_yield/calc','RelativeYieldController@calc');

Route::resource('relative_yield', 'RelativeYieldController');

Route::get('/users/logins', 'UserController@logins');
Route::resource('users', 'UserController');

app/Http/Controllers/FarmersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Farmer;
use App\Land;
use App\Royalties;
use App\Models\Community;
use App\Models\Region;
use App\Models\Province;

class FarmersController extends Controller
{
    public function index()
    {
        $farmer = Farmer::All();
        return View('farmers.index',compact('farmer'));
    }

    /**
     * Vista para crear usuario
     */
    public function create()
    {	

        $region = Region::All();

        return View('farmers.create', compact('region'));
    }

    /**
     * Agrega nuevo usuario en base de datos
     */
    public function store(Request $request)
    {
        
        Farmer::create($request->all());

        return back()->with('success','Agricultor creado correctamente.');
    }


    /**
     * Vista para editar usuario
     */
    public function edit($id)
    {
        $farmer = Farmer::find($id);
        $region = Region::All();
        $communities = Community::All();
        $provinces = Province::All();

        return view('farmers.edit',compact('region','farmer', 'communities', 'provinces'));
    }

    /**
     * Actualiza usuario en base de datos
     */
    public function update(Request $request, $id)
    {

        Farmer::find($id)->update($request->all());

        return back()->with('success','Usuario editado corectamente.');
    }

    /**
     * Elimina usuario
     */
    public function destroy(Farmer $farmer)
    {
        Farmer::find($farmer->id)->delete();
     
        return back()->with('success','Usuario eliminado correctamente.');
    }

    public function getProvinces(){
        $region_id = $_GET["region_id"];
        $provinces = Province::where('region_id','=',$region_id)->get();
        return json_encode($provinces);
    }

    public function getCommunities(){
        if(isset($_GET["province_id"])){
            $province_id = $_GET["province_id"];
            $communities = Community::where('province_id','=',$province_id)->get();
        }else{
            $communities = Community::where('country_id','=', $_GET['country_id'])->get();
        }
        
        return json_encode($communities);
    }

     public function getLands(){
        $farmer_id = $_GET["farmer_id"];
        $lands = Land::where('farmer_id',$farmer_id)->get();
        return json_encode($lands);
    }

    
}

resources/views/farmers/create.blade.php
@extends('layouts.app')

@section('content')

<div class="m-portlet m-portlet--head-solid-bg m-portlet--rounded">
    <div class="m-portlet__head">
        <div class="m-portlet__head-caption">
            <div class="m-portlet__head-title">
                <h3 class="m-portlet__head-text">
                    Add Farmer
                </h3>
            </div>          
        </div>
    </div>
    <div class="m-portlet__body">
        {!! Form::open(array('route' => 'farmers.store','method'=>'POST','id' => 'FormCreateFarmer')) !!}
            @include('farmers.form')
            <button type="submit" class="btn btn-primary">Add Farmer</button>
        {!! Form::close() !!}
    </div>
</div>

<script>
    



    function initAutocomplete() {
        var map = new google.maps.Map(document.getElementById('map'), {
            center: {lat: -41.21843, lng: -73.0178829},
            zoom: 10,
            mapTypeId: 'satellite'
        });

        var markers = [];

        // Create the search box and link it to the UI element.
        var input = document.getElementById('pac-input');
        var searchBox = new google.maps.places.SearchBox(input);
        map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

        // Bias the SearchBox results towards current map's viewport.
        map.addListener('bounds_changed', function() {
            searchBox.setBounds(map.getBounds());
        });

        // Listen for the event fired when the user selects a prediction and retrieve
        // more details for that place.
        searchBox.addListener('places_changed', function() {
            var places = searchBox.getPlaces();
            if (places.length == 0) {
                return;
            }
            

            // For each place, get the icon, name and location.
            var bounds = new google.maps.LatLngBounds();
            places.forEach(function(place) {
                if (!place.geometry) {
                    console.log("Returned place contains no geometry");
                    return;
                }

                var latitude = place.geometry.location.lat();
                var longitude = place.geometry.location.lng(); 
                $("input[name=latitude]").val(latitude)
                $("input[name=longitude]").val(longitude)

                var marker = new google.maps.Marker({
                    map: map,
                    title: place.name,
                    position: place.geometry.location,
                    draggable: true
                });

                google.maps.event.addListener(marker, 'dragend', function (event) {
                    $("input[name=latitude]").val(this.getPosition().lat())
                    $("input[name=longitude]").val(this.getPosition().lng())
                }); 


                // Create a marker for each place.
                markers.push(marker);

                if (place.geometry.viewport) {
                    // Only geocodes have viewport.
                    bounds.union(place.geometry.viewport);
                } else {
                    bounds.extend(place.geometry.location);
                }
            });
            map.fitBounds(bounds);

            
        });


    }


</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAd3yh0ivl1dLQraSDf5r-_9N484zc7bTQ&libraries=places&callback=initAutocomplete">


@endsection

resources/views/farmers/edit.blade.php
@extends('layouts.app')
@section('content')


<div class="m-portlet m-portlet--head-solid-bg m-portlet--rounded">
    <div class="m-portlet__head">
        <div class="m-portlet__head-caption">
            <div class="m-portlet__head-title">
                <h3 class="m-portlet__head-text">
                    Update Farmer</b>
                </h3>
            </div>          
        </div>
        <div class="m-portlet__head-tools">
            <ul class="m-portlet__nav">
                <li class="m-portlet__nav-item">
                    <a href="{{ route('farmers.index') }}" class="m-portlet__nav-link btn btn-outline-primary m-btn m-btn--outline-2x ">
                        Back
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="m-portlet__body">
        {!! Form::model($farmer, ['method' => 'PATCH','id' => 'FormEdit','route' => ['farmers.update', $farmer->id]]) !!}
		    @include('farmers.form')
		    <button type="submit" class="btn btn-primary">Edit</button>
		{!! Form::close() !!}
    </div>
</div>
<script>
    $(document).ready(function() {
        $("#FormEdit").validate()
	});
</script>

<script>
    function initAutocomplete() {

        console.log($("input[name=latitude]").val())

        selected_lat = $("input[name=latitude]").val()
        selected_lon = $("input[name=longitude]").val()
        var myLatlng = new google.maps.LatLng(parseFloat(selected_lat), parseFloat(selected_lon));
        var last_marker = new google.maps.Marker({
            position: myLatlng,
            title:"Hello World!"
        });

        var map = new google.maps.Map(document.getElementById('map'), {
            center: {lat: parseFloat(selected_lat), lng: parseFloat(selected_lon)},
            zoom: 10,
            mapTypeId: 'satellite'
        });

        var markers = [];
        last_marker.setMap(map);

        // Create the search box and link it to the UI element.
        var input = document.getElementById('pac-input');
        var searchBox = new google.maps.places.SearchBox(input);
        map.controls[google.maps.ControlPosition.TOP_LEFT].push(input);

        // Bias the SearchBox results towards current map's viewport.
        map.addListener('bounds_changed', function() {
            searchBox.setBounds(map.getBounds());
        });

        // Listen for the event fired when the user selects a prediction and retrieve
        // more details for that place.
        searchBox.addListener('places_changed', function() {
            var places = searchBox.getPlaces();
            if (places.length == 0) {
                return;
            }
            

            // For each place, get the icon, name and location.
            var bounds = new google.maps.LatLngBounds();
            places.forEach(function(place) {
                if (!place.geometry) {
                    console.log("Returned place contains no geometry");
                    return;
                }

                var latitude = place.geometry.location.lat();
                var longitude = place.geometry.location.lng(); 
                $("input[name=latitude]").val(latitude)
                $("input[name=longitude]").val(longitude)

                var marker = new google.maps.Marker({
                    map: map,
                    title: place.name,
                    position: place.geometry.location,
                    draggable: true
                });

                google.maps.event.addListener(marker, 'dragend', function (event) {
                    $("input[name=latitude]").val(this.getPosition().lat())
                    $("input[name=longitude]").val(this.getPosition().lng())
                }); 


                // Create a marker for each place.
                markers.push(marker);

                if (place.geometry.viewport) {
                    // Only geocodes have viewport.
                    bounds.union(place.geometry.viewport);
                } else {
                    bounds.extend(place.geometry.location);
                }
            });
            map.fitBounds(bounds);
            
        });
    }


</script>
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAd3yh0ivl1dLQraSDf5r-_9N484zc7bTQ&libraries=places&callback=initAutocomplete">
</script>
@endsection

resources/views/farmers/form.blade.php
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md-3">
        <div class="form-group">
            <label>Name:</label>
            {!! Form::text('name', null, array('placeholder' => 'Enter Name','class' => 'form-control required')) !!}
        </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-3">
        <div class="form-group">
            <label>ID:</label>
            {!! Form::text('rut', null, array('placeholder' => 'Enter ID','class' => 'form-control required rut')) !!}
        </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-3">
        <div class="form-group">
            <label>Email:</label>
            {!! Form::text('email', null, array('placeholder' => 'Enter Email','class' => 'form-control email')) !!}
        </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-3">
        <div class="form-group">
            <label>Telephone:</label>
            {!! Form::text('phone', null, array('placeholder' => 'Enter Telephone','class' => 'form-control number')) !!}
        </div>
    </div>
    
    <div class="col-xs-6 col-sm-6 col-md-4">
        <div class="form-group">
            <label>Description:</label>
            {!! Form::text('description', null, array('placeholder' => 'Enter Description','class' => 'form-control ')) !!}
        </div>
    </div>
    <div class="col-xs-6 col-sm-6 col-md-4">
        <label for="name">Region</label>
        <select class="form-control required" name="region_id">
            <option value="">Select Region</option>
            @foreach($region as $v)
                <option value="{{$v->id}}">{{$v->name}}</option>
            @endforeach
        </select>
    </div>

    <div class="col-xs-6 col-sm-6 col-md-4">
        {!!Form::label('Province')!!}
        {!!Form::select('province_id',array(), null,['class' => 'form-control required select2 provinces','placeholder' => 'Select Province'])!!}
    </div>
    <div class="col-xs-6 col-sm-6 col-md-4">
        {!!Form::label('Community')!!}
        {!!Form::select('community_id',array(), null,['class' => 'form-control required select2','placeholder' => 'Select Community'])!!}
    </div>
    <div class="col-lg-4">
        <div class="form-group">
            <label>Latitude:</label>
            {!! Form::text('latitude', null, array('placeholder' => 'Select a point on the map','class' => 'form-control', 'readonly' => 'readonly')) !!}
        </div>
    </div>
    <div class="col-lg-4">
        <div class="form-group">
            <label>Longitude:</label>
            {!! Form::text('longitude', null, array('placeholder' => 'Select a point on the map','class' => 'form-control', 'readonly' => 'readonly')) !!}
        </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12">
        <div id="google_maps">
            <input id="pac-input" class="controls" type="text" placeholder="Enter address">
            <div id="map" style="height: 400px;width: 100%;margin-bottom: 30px;"></div>
        </div>
    </div>
</div>
    <!--
    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            <strong>Body:</strong>
            {!! Form::textarea('body', null, array('placeholder' => 'Body','class' => 'form-control','style'=>'height:150px')) !!}
        </div>
    </div>-->

<script>
    $(document).ready(function(){
        $("select[name=region_id]").change(function(){
            region_id = $(this).val()
            if(region_id != ""){
                $("select[name=province_id]").html('<option value="">Select Province</option>')
                $("select[name=community_id]").html('<option value="">Select Community</option>')
                $.getJSON("/farmers/provinces?region_id="+region_id, function( data ) {
                    var items = [];
                    $.each( data, function( key, val ) {
                        $("select[name=province_id]").append( "<option value='" + val.id + "'>" + val.name + "</option>" );
                    });
                    $("select[name=province_id]").removeAttr("disabled")
                    
                });
            }
        })

        $("select[name=province_id]").change(function(){
            province_id = $(this).val()
            if(province_id != ""){
                $("select[name=community_id]").html('<option value="">Select City</option>')
                $.getJSON( "/farmers/communities?province_id="+province_id, function( data ) {
                    var items = [];
                    $.each( data, function( key, val ) {
                        $("select[name=community_id]").append( "<option value='" + val.id + "'>" + val.name + "</option>" );
                        $("select[name=community_id_dynamic]").append( "<option value='" + val.id + "'>" + val.name + "</option>" );
                    });
                    $("select[name=community_id]").removeAttr("disabled")
                });
            }
        })

        $("select[name=community_id]").change(function(){
            var text = $("select[name=community_id] option:selected").text()
            $("#pac-input").val(text).change()
        })
    })
</script>

resources/views/farmers/index.blade.php
@extends('layouts.app')
@section('content')
<div class="m-portlet m-portlet--head-solid-bg m-portlet--rounded">
    <div class="m-portlet__head">
        <div class="m-portlet__head-caption">
            <div class="m-portlet__head-title">
                <span class="m-portlet__head-icon">
                    <i class="flaticon-list"></i>
                </span>
                <h3 class="m-portlet__head-text">
                    Farmers
                </h3>
            </div>          
        </div>
        <div class="m-portlet__head-tools">
            <ul class="m-portlet__nav">
                <li class="m-portlet__nav-item">
                    <a href="{{ route('farmers.create') }}" class="m-portlet__nav-link btn btn-outline-primary m-btn m-btn--outline-2x ">
                        Add Farmer
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="m-portlet__body">
        <table class="table table-striped- table-bordered table-hover table-checkable datatables_p">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Community</th>
                    <th>Description</th>
                    <th>Royalty</th>
                    <th style="width:350px"></th>
                </tr>
            </thead>
            <tbody>
                @if(!empty($farmer))
                    @foreach($farmer as $record)
                        <tr>
                            <td><b>{{ $record->rut }}</b></td>
                            <td><b>{{ $record->name }}</b></td>
                            <td><b>{{ $record->email }}</b></td>
                            <td><b>{{ $record->community->name }}</b></td>
                            <td><b>{{ $record->description }}</b></td>
                            @if($record->getStatusPayment() == 1 )
                            
                                <td><span style="float:right" class="m-badge m-badge--info m-badge--wide">Up to date</span></td>
                            @else
                                <td><span style="float:right" class="m-badge m-badge--danger m-badge--wide">Amount owing</span></td>
                            @endif
                            <td>
                                <center>
                                    <a class="btn btn-outline-info btn-sm" href="{{ route('royalties.show',$record->id) }}">Royalties</a>
                                    <a class="btn btn-outline-success btn-sm" href="{{ route('farmers.edit',$record->id) }}">Edit</a>
                                    {!! Form::open(['method' => 'DELETE','route' => ['farmers.destroy', $record->id],'style'=>'display:inline']) !!}
                                    {!! Form::submit('Delete', ['class' => 'btn btn-outline-danger btn-sm btn-delete']) !!}
                                    {!! Form::close() !!}
                                </center>
                            </td>
                        </tr>
                    @endforeach
                @endif
            </tbody>
        </table>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function(){
        
    })
</script>
@endsection