routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Models\Feature;

Route::get('/', 'HomeController@index');
Route::get('/import', 'HomeController@import');
Route::post('/import', 'HomeController@importExcel');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/features/add-value', function () {
	return View('features._add-value',['id' => $_GET['id']]);
});

Route::get('/features/get-values', function () {
	$feature = Feature::find($_GET['id']);
	return View('features._get-values',['feature' => $feature]);
});
Route::get('/varities/exporData', 'VarityController@check_db');
Route::get('/varities/searchHome', 'VarityController@searchHome');
Route::get('/varities/searchHomeCrossing', 'VarityController@searchHomeCrossing');
Route::get('/varities/addValues', 'VarityController@addValues');
Route::get('/varities/addFeature', 'VarityController@addFeature');
Route::get('/blocks/addFeature', 'BlockController@addFeature');
Route::post('/varities/saveCharacteristics', 'VarityController@saveCharacteristics');
Route::post('/varities/uploadPhoto', 'VarityController@uploadPhoto');
Route::get('/varities/ancesters/{id}/{maxlevel}/{level}', 'VarityController@ancesters');
Route::put('/varities/financial/{varity}', 'VarityController@financialInfo')->name('varities.financialInfo');
Route::resource('varities', 'VarityController');


Route::get('/crossings/zonashow/{id?}', 'CrossingController@zonashow')->name('crossings.zonashow');
Route::get('/crossings/zonaedit/{id?}', 'CrossingController@zonaedit')->name('crossings.zonaedit');
Route::get('/crossings/zonacreate/{id?}', 'CrossingController@zonacreate')->name('crossings.zonacreate');
Route::post('/crossings/zonacreate', 'CrossingController@zonastore')->name('crossings.zonacreate');
Route::get('/crossings/mapout', 'CrossingController@mapout');
Route::get('/crossings/zona', 'CrossingController@zona');
Route::get('/crossings/saveObservations', 'CrossingController@saveObservations');
Route::post('/crossings/uploadPhoto', 'CrossingController@uploadPhoto');
Route::get('/crossings/deleteCodify', 'CrossingController@deleteCodify');
Route::get('/crossings/generateCodify', 'CrossingController@generateCodify');
Route::get('/crossings/codify/{id}', 'CrossingController@codify');
Route::get('/crossings/finishCodify/{id}', 'CrossingController@finishCodify');
Route::get('/crossings/codedJSON/', 'CrossingController@codedJSON');
Route::get('/crossings/items/', 'CrossingController@items');
Route::post('/crossings/saveCodify/', 'CrossingController@saveCodify');
Route::post('/crossings/saveCharacteristics', 'CrossingController@saveCharacteristics');
Route::get('/crossings/check_ancester/', 'CrossingController@check_ancester');


Route::post('/blocks/saveShowFarms','BlockController@saveShowFarms');
Route::get('/blocks/modCaracteristicas','BlockController@modCaracteristicas');
Route::get('/blocks/saveObservation','BlockController@saveObservation');
Route::get('/blocks/getCaracteristicas','BlockController@getCaracteristicas');	
Route::get('/blocks/getFotos','BlockController@getFotos');
Route::get('/blocks/codify','BlockController@codify');
Route::get('/blocks/print','BlockController@print');
Route::get('/blocks/move_position','BlockController@move_position');
Route::get('/blocks/info_to_compare','BlockController@info_to_compare');
Route::get('/blocks/deleteCodify/{id}','BlockController@deleteCodify');
Route::get('/blocks/getDataChar/','BlockController@getDataChar');
Route::get('/blocks/reorder/{id}','BlockController@reorder');
Route::get('/blocks/discard/','BlockController@discard');
Route::get('/blocks/review/','BlockController@review');
Route::get('/blocks/export/{id}','BlockController@export');
Route::get('/blocks/send_to_blocks','BlockController@send_to_blocks');
Route::get('/blocks/trash','BlockController@trash');
Route::get('/blocks/show_trash/{id}','BlockController@show_trash');
Route::get('/blocks/mark_offline/','BlockController@mark_offline');
Route::resource('blocks', 'BlockController');

Route::get('/mapouts/generateCodify/{id}','MapoutController@generateCodify');
Route::get('/mapouts/deleteCodify/{id}','MapoutController@deleteCodify');
Route::post('/mapouts/updatePosition', 'MapoutController@updatePosition')->name('mapouts.updatePosition');
Route::post('/mapouts/addPositions', 'MapoutController@addPositions')->name('mapouts.addPositions');
Route::resource('mapouts', 'MapoutController');
Route::resource('crossings', 'CrossingController');
Route::resource('features', 'FeatureController');

Route::get("farmers/provinces/", "FarmersController@getProvinces");
Route::get("farmers/communities/", "FarmersController@getCommunities");
Route::get("farmers/lands/", "FarmersController@getLands");

Route::resource('farmers', 'FarmersController');
Route::resource('companies', 'CompanyController');
Route::resource('lands', 'LandController');
Route::resource('traceability', 'TraceabilityController');
Route::get("royalties/create/{farmer_id}", "RoyaltiesController@create");

Route::resource('royalties', 'RoyaltiesController');

Route::get('/results/getData/','ResultsController@getData');
Route::get('/results/crossings/','ResultsController@crossings');
Route::get('/results/fries/','ResultsController@fries');
Route::get('/results/searchCrossings/','CrossingController@searchCrossings');
Route::get('/results/getVaritiesFromBlock/','ResultsController@getVaritiesFromBlock');
Route::get('/results/getChildrensFromVarity/','ResultsController@getChildrensFromVarity');
Route::get('/results/getCaracteristicas/','ResultsController@getCaracteristicas');
Route::get('/results/modCaracteristicas','ResultsController@modCaracteristicas');
Route::any('/fries/save/','BlockController@saveDataFries');			
Route::get('/fries/getData/','BlockController@getDataFries');
Route::any('/fries/updateFries/','BlockController@updateDataFries');			

Route::get('/results/preview_report/','ResultsController@preview_report');
Route::get('/results/load_preview/','ResultsController@load_preview');
Route::any('/results/report/','ResultsController@report');
Route::get('/results/getVarities/','ResultsController@varities');
Route::get('/results/info_to_compare/','ResultsController@info_to_compare');
Route::get('/results/getBlocksByYear/','ResultsController@getBlocksByYear');
Route::get('/results/getVarityByname/','ResultsController@getVarityByname');
Route::get('/results/getVarityBynameInfo/','ResultsController@getVarityBynameInfo');
Route::get('/results/getDataFeature/','ResultsController@getDataFeature');
Route::get('/results/stadistics/','ResultsController@stadistics');

Route::resource('results', 'ResultsController');

Route::resource('std_market', 'StdMarketController');


Route::DELETE('/greenhouse/destroy_greenhouse', 'GreenHouseController@destroy_greenhouse')->name('greenhouse.destroy_greenhouse');
Route::PATCH('/greenhouse/update_greenhouse', 'GreenHouseController@update_greenhouse')->name('greenhouse.update_greenhouse');
Route::get('/greenhouse/asociate_crossing/{id}','GreenHouseController@asociate_crossing')->name('greenhouse.asociate_crossing');
Route::get('/greenhouse/crossings_add/','GreenHouseController@crossings_add');
Route::get('/greenhouse/crossings_added/{id}','GreenHouseController@crossings_added');
Route::post('/greenhouse/store_crossings', 'GreenHouseController@store_crossings');
Route::post('/greenhouse/delete_crossings', 'GreenHouseController@delete_crossings');


Route::get('/greenhouse/generateCodify/{id}','GreenHouseController@generateCodify');
Route::get('/greenhouse/show_mobile/{id}','GreenHouseController@show_mobile');
Route::get('/greenhouse/crossings_ok/{id}','GreenHouseController@crossings_ok');
Route::get('/greenhouse/crossings_list/{id}','GreenHouseController@crossings_list');
Route::get('/greenhouse/show_mobile/{id}','GreenHouseController@show_mobile');
Route::get('/public/draw_greenhouse/{id}','GreenHouseController@draw_greenhouse');
Route::get('draw_greenhouse/{id}','GreenHouseController@draw_greenhouse');
Route::get('/greenhouse/deleteCodify/{id}','GreenHouseController@deleteCodify');
Route::post('/greenhouse/updatePosition', 'GreenHouseController@updatePosition')->name('greenhouse.updatePosition');
Route::post('/greenhouse/addPositions', 'GreenHouseController@addPositions')->name('greenhouse.addPositions');
Route::get('/greenhouse/switch/{varity_id}/{father_id}/{mother_id}','GreenHouseController@switchFathers');
Route::get('/greenhouse/polen/{father_id}/{mother_id}/{status}','GreenHouseController@savePolen');
Route::get('/greenhouse/berries/{id}/{nro_berries}','GreenHouseController@save_berries');
Route::get('/greenhouse/glasses/{id}/{nro_glases}','GreenHouseController@save_glasses');
Route::get('/greenhouse/get_data_chart','GreenHouseController@get_data_chart');
Route::resource('greenhouse', 'GreenHouseController');

Route::get('/relative_yield/calc','RelativeYieldController@calc');

Route::resource('relative_yield', 'RelativeYieldController');

Route::get('/users/logins', 'UserController@logins');
Route::resource('users', 'UserController');

app/GreenHouse.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class GreenHouse extends Model
{
    protected $table = 'greenhouse';
    //
}

resources/views/greenhouse/crossings.blade.php
@extends('layouts.app')
@section('content')
<script src="https://cdn.amcharts.com/lib/4/core.js"></script>
<script src="https://cdn.amcharts.com/lib/4/charts.js"></script>
<script src="https://cdn.amcharts.com/lib/4/maps.js"></script>
<script src="https://cdn.amcharts.com/lib/4/geodata/usaAlbersLow.js"></script>
<script src="https://cdn.amcharts.com/lib/4/themes/animated.js"></script>
<style type="text/css">
    #chartdiv {
      width: 100%;
      height: 3200px;
    }
</style>
<div class="m-portlet m-portlet--head-solid-bg m-portlet--rounded">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <div class="m-portlet__head">
        <div class="m-portlet__head-caption">
            <div class="m-portlet__head-title">
                <span class="m-portlet__head-icon">
                    <i class="flaticon-calendar"></i>
                </span>
                <h3 class="m-portlet__head-text">
                    {{ $greenhouse->name }}
                    <input type="hidden" id="id_greenhouse" value="{{ $greenhouse->id }}">
                </h3>
            </div>          
        </div>
        <div class="m-portlet__head-tools">
            <ul class="m-portlet__nav">
                <li class="m-portlet__nav-item">
                    
                </li>
            </ul>
        </div>
    </div>
    <div class="m-portlet__body">
        <ul class="nav nav-tabs nav-fill" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" data-toggle="tab" href="#add_crossings">Add Crossings</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#added_crossings">List of Added Crossings</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#resumen_crossings">Summary of Added Crossings</a>
            </li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active show" id="add_crossings" role="tabpanel">
            </div>
            <div class="tab-pane" id="added_crossings" role="tabpanel">
            </div>
            <div class="tab-pane" id="resumen_crossings" role="tabpanel">
                <dir class="row">
                    <div class="col-md-3">
                        <input placeholder="Fecha Desde" class="form-control timepicker" required="" id="desde" name="desde" type="text">
                    </div>
                     <div class="col-md-3">
                        <input placeholder="Fecha Hasta" class="form-control timepicker" required="" id="hasta" name="hasta" type="text">
                    </div>
                    <button type="button" class="btn btn-info" onclick="filtrar()"><i class="fa fa-search"></i> Filter</button>
                </dir>
                
                <div id="chartdiv"></div>       
            </div>
        </div>
    </div>
</div>



<script type="text/javascript">
    
    array_find = [];
    array_delete = [];

    $(document).ready(function(){

        table_crossings = $("#table_crossings").DataTable({
            bPaginate:false,
            
        })

        $(".timepicker").datetimepicker({
            orientation: "bottom",
        });


        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        })

        draw_crossings_add()
        draw_crossings_added();

        var data_chart = <?= json_encode($data_chart); ?>;
        draw_chart(data_chart);
    })

    draw_chart = function(usData){
        am4core.useTheme(am4themes_animated);
        // Themes end

        var mainContainer = am4core.create("chartdiv", am4core.Container);
        mainContainer.width = am4core.percent(100);
        mainContainer.height = am4core.percent(100);
        mainContainer.layout = "horizontal";

        var maleChart = mainContainer.createChild(am4charts.XYChart);
        maleChart.paddingRight = 0;
        maleChart.data = JSON.parse(JSON.stringify(usData));

        // Create axes
        var maleCategoryAxis = maleChart.yAxes.push(new am4charts.CategoryAxis());
        maleCategoryAxis.dataFields.category = "age";
        maleCategoryAxis.renderer.grid.template.location = 0;
        //maleCategoryAxis.renderer.inversed = true;
        maleCategoryAxis.renderer.minGridDistance = 15;

        var maleValueAxis = maleChart.xAxes.push(new am4charts.ValueAxis());
        maleValueAxis.renderer.inversed = true;
        maleValueAxis.min = 0;
        maleValueAxis.max = 20;
        maleValueAxis.strictMinMax = true;

        maleValueAxis.numberFormatter = new am4core.NumberFormatter();
        maleValueAxis.numberFormatter.numberFormat = "#.#'%'";

        // Create series
        var maleSeries = maleChart.series.push(new am4charts.ColumnSeries());
        maleSeries.dataFields.valueX = "male";
        maleSeries.dataFields.valueXShow = "percent";
        maleSeries.calculatePercent = true;
        maleSeries.dataFields.categoryY = "age";
        maleSeries.interpolationDuration = 1000;
        maleSeries.columns.template.tooltipText = "{categoryY}: {valueX} ({valueX.percent.formatNumber('#.0')}%)";
        var labelBullet = maleSeries.bullets.push(new am4charts.LabelBullet())
        labelBullet.label.horizontalCenter = "right";
        labelBullet.label.text = "{valueX}";
        labelBullet.label.textAlign = "end";
        labelBullet.label.dx = -10;
        //maleSeries.sequencedInterpolation = true;


        var femaleChart = mainContainer.createChild(am4charts.XYChart);
        femaleChart.paddingLeft = 0;
        femaleChart.data = JSON.parse(JSON.stringify(usData));

        // Create axes
        var femaleCategoryAxis = femaleChart.yAxes.push(new am4charts.CategoryAxis());
        femaleCategoryAxis.renderer.opposite = true;
        femaleCategoryAxis.dataFields.category = "age";
        femaleCategoryAxis.renderer.grid.template.location = 0;
        femaleCategoryAxis.renderer.minGridDistance = 15;

        var femaleValueAxis = femaleChart.xAxes.push(new am4charts.ValueAxis());
        femaleValueAxis.min = 0;
        femaleValueAxis.max = 20;
        femaleValueAxis.strictMinMax = true;
        femaleValueAxis.numberFormatter = new am4core.NumberFormatter();
        femaleValueAxis.numberFormatter.numberFormat = "#.#'%'";
        femaleValueAxis.renderer.minLabelPosition = 0.01;

        // Create series
        var femaleSeries = femaleChart.series.push(new am4charts.ColumnSeries());
        femaleSeries.dataFields.valueX = "female";
        femaleSeries.dataFields.valueXShow = "percent";
        femaleSeries.calculatePercent = true;
        femaleSeries.fill = femaleChart.colors.getIndex(4);
        femaleSeries.stroke = femaleSeries.fill;
        //femaleSeries.sequencedInterpolation = true;
        femaleSeries.columns.template.tooltipText = "{categoryY}: {valueX} ({valueX.percent.formatNumber('#.0')}%)";
        femaleSeries.dataFields.categoryY = "age";
        femaleSeries.interpolationDuration = 1000;

        var labelBullet = femaleSeries.bullets.push(new am4charts.LabelBullet())
        labelBullet.label.horizontalCenter = "right";
        labelBullet.label.text = "{valueX}";
        labelBullet.label.textAlign = "end";
        labelBullet.label.dx = 10;
    }

    draw_crossings_add = function(){
        $('#add_crossings').empty()

        $.ajax({
          url:  "/greenhouse/crossings_add",
          success: function(data) {
            $('#add_crossings').empty().html(data);
          }
        });
    } 

    filtrar =  function(){
        var params = {
            desde : $("#desde").val(),
            hasta : $("#hasta").val(),
            id: $("#id_greenhouse").val(),
        }

        $.ajax({
            url: '/greenhouse/get_data_chart',
            type: 'GET',
            dataType: 'json',
            data: params
        }).done(function(data) {
            if(data){
                if(data.length > 0){
                    draw_chart(data);
                }else{
                    sweetAlert("No data found for the dates entered")
                }
            }
        })
    }

    draw_crossings_added = function(){
        $('#added_crossings').empty()

        $.ajax({
          url:  "/greenhouse/crossings_added/"+$("#id_greenhouse").val(),
          success: function(data) {
            $('#added_crossings').empty().html(data);
          }
        });
    } 

    registrarCheck = function(indice){
        var item = {};
        
        for (var i = 0; i < array_find.length; i++) {
            if ( (array_find[i]['IDVARITY'] == indice)) {
                array_find.splice(i, 1);
            };
        };

        if ( $("#index_"+indice).is(':checked') ) {
            item['IDVARITY'] = indice;
            array_find.push(item);
        }
    }

    seleccionar = function(){
        $.ajax({
            url: '/greenhouse/store_crossings',
            type: 'POST',
            dataType: 'json',
            data: {arr_crossings : array_find, greenhouse_id: $("#id_greenhouse").val(),_token: "{{ csrf_token() }}"},
        }).done(function(data) {
            if(data){
                sweetAlert("Record entered successfully")
                draw_crossings_add()
                draw_crossings_added()
            }
        })
    }

    toDelete = function(indice){
        var item = {};
        
        for (var i = 0; i < array_delete.length; i++) {
            if ( (array_delete[i]['IDVARITY'] == indice)) {
                array_delete.splice(i, 1);
            };
        };

        if ( $("#_dindex_"+indice).is(':checked') ) {
            item['IDVARITY'] = indice;
            array_delete.push(item);
        }
    }

    delete_selected = function(){
        $.ajax({
            url: '/greenhouse/delete_crossings',
            type: 'POST',
            dataType: 'json',
            data: {arr_crossings : array_delete, greenhouse_id: $("#id_greenhouse").val(),_token: "{{ csrf_token() }}"},
        }).done(function(data) {
            if(data){
                sweetAlert("Record deleted successfully")
                draw_crossings_add()
                draw_crossings_added()
            }
        })
    }
</script>
@endsection

resources/views/greenhouse/index.blade.php
@extends('layouts.app')
@section('content')
<div class="m-portlet m-portlet--head-solid-bg m-portlet--rounded">
    <div class="m-portlet__head">
        <div class="m-portlet__head-caption">
            <div class="m-portlet__head-title">
                <span class="m-portlet__head-icon">
                    <i class="flaticon-calendar"></i>
                </span>
                <h3 class="m-portlet__head-text">
                    Greenhouses
                </h3>
            </div>          
        </div>
    </div>

    <div class="m-portlet__body">

         {!! Form::open(array('class' => 'm-form','route' => 'greenhouse.store','method'=>'POST','id' => 'FormCreate')) !!}
                <div class="row" >
                    <div class="col-md-3">
                        <strong>Year:</strong>
                        {!! Form::text('name', null, array('placeholder' => 'Ex. 2020 Season','class' => 'form-control  required', 'required' => '')) !!}
                    </div>
                </div>
                 <button type="submit" class="m-portlet__nav-link btn btn-outline-primary m-btn m-btn--outline-2x " style="margin-bottom: 25px;">
                    Add Greenhouse
                </button>                
            {!! Form::close() !!}

            {!! Form::open(array('class' => 'm-form','route' => ['greenhouse.update_greenhouse', 0],'method'=>'PATCH','id' => 'form_update')) !!}
                <div class="row" >
                    <div class="col-md-3">
                        <strong>Año:</strong>
                        {!! Form::text('name_to_edit', null, array('placeholder' => 'Ex. 2020 Season','class' => 'form-control  required', 'required' => 'true', 'id' => 'name_to_edit' )) !!}
                        <strong>Nombre:</strong>
                    </div>
                </div>
                <input type="hidden" name="id" id="id">
                 <button type="submit" class="m-portlet__nav-link btn btn-outline-primary m-btn m-btn--outline-2x " style="margin-bottom: 25px;">
                    Update Greenhouse
                </button>     
                <button type="button"  onclick="store()" class="m-portlet__nav-link btn btn-outline-danger m-btn m-btn--outline-2x " style="margin-top: 5px;">
                    Cancel
                </button>            
            {!! Form::close() !!}


        <table class="table table-striped- table-bordered table-hover table-checkable datatables_p">
            <thead>
                <tr>
                    <th>Year</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @if(!empty($greenhouse))
                    @foreach($greenhouse as $record)
                        <tr>
                            <td><b>{{ $record->name }}</b></td>
                            <td>
                                 <center>
                                    <a class="btn btn-outline-info btn-sm" href="{{ route('greenhouse.show',$record->id) }}">Ver</a>
                                     <a class="btn btn-outline-success btn-sm" href="#" onclick="edit('{{$record->id}}','{{$record->name}}')">Edit</a>
                                    {!! Form::open(['method' => 'DELETE','route' => ['greenhouse.destroy_greenhouse', $record->id],'style'=>'display:inline']) !!}
                                    <input type="hidden" name="to_delete" value="{{$record->id}}">
                                    {!! Form::submit('Delete', ['class' => 'btn btn-outline-danger btn-sm btn-delete']) !!}
                                    {!! Form::close() !!}
                                    <a class="btn btn-outline-info btn-sm" href="{{ route('greenhouse.asociate_crossing',$record->id) }}">Crossings</a>

                                </center>
                            </td>
                        </tr>
                    @endforeach
                @endif
            </tbody>
        </table>
    </div>
</div>
<script>
    $(document).ready(function() {

        $(".table").DataTable()
        $("#form_update").hide()

        edit = function(a,b){
            $("#form_update").show()
            $("#FormCreate").hide()
            $("#name_to_edit").val(b)
            $("#id").val(a)
        }

        store = function(){
            $("#form_update").hide()
            $("#FormCreate").show()
        }
    });
</script>
@endsection