routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Models\Feature;

Route::get('/', 'HomeController@index');
Route::get('/import', 'HomeController@import');
Route::post('/import', 'HomeController@importExcel');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/features/add-value', function () {
	return View('features._add-value',['id' => $_GET['id']]);
});

Route::get('/features/get-values', function () {
	$feature = Feature::find($_GET['id']);
	return View('features._get-values',['feature' => $feature]);
});
Route::get('/varities/exporData', 'VarityController@check_db');
Route::get('/varities/searchHome', 'VarityController@searchHome');
Route::get('/varities/searchHomeCrossing', 'VarityController@searchHomeCrossing');
Route::get('/varities/addValues', 'VarityController@addValues');
Route::get('/varities/addFeature', 'VarityController@addFeature');
Route::get('/blocks/addFeature', 'BlockController@addFeature');
Route::post('/varities/saveCharacteristics', 'VarityController@saveCharacteristics');
Route::post('/varities/uploadPhoto', 'VarityController@uploadPhoto');
Route::get('/varities/ancesters/{id}/{maxlevel}/{level}', 'VarityController@ancesters');
Route::put('/varities/financial/{varity}', 'VarityController@financialInfo')->name('varities.financialInfo');
Route::resource('varities', 'VarityController');


Route::get('/crossings/zonashow/{id?}', 'CrossingController@zonashow')->name('crossings.zonashow');
Route::get('/crossings/zonaedit/{id?}', 'CrossingController@zonaedit')->name('crossings.zonaedit');
Route::get('/crossings/zonacreate/{id?}', 'CrossingController@zonacreate')->name('crossings.zonacreate');
Route::post('/crossings/zonacreate', 'CrossingController@zonastore')->name('crossings.zonacreate');
Route::get('/crossings/mapout', 'CrossingController@mapout');
Route::get('/crossings/zona', 'CrossingController@zona');
Route::get('/crossings/saveObservations', 'CrossingController@saveObservations');
Route::post('/crossings/uploadPhoto', 'CrossingController@uploadPhoto');
Route::get('/crossings/deleteCodify', 'CrossingController@deleteCodify');
Route::get('/crossings/generateCodify', 'CrossingController@generateCodify');
Route::get('/crossings/codify/{id}', 'CrossingController@codify');
Route::get('/crossings/finishCodify/{id}', 'CrossingController@finishCodify');
Route::get('/crossings/codedJSON/', 'CrossingController@codedJSON');
Route::get('/crossings/items/', 'CrossingController@items');
Route::post('/crossings/saveCodify/', 'CrossingController@saveCodify');
Route::post('/crossings/saveCharacteristics', 'CrossingController@saveCharacteristics');
Route::get('/crossings/check_ancester/', 'CrossingController@check_ancester');


Route::post('/blocks/saveShowFarms','BlockController@saveShowFarms');
Route::get('/blocks/modCaracteristicas','BlockController@modCaracteristicas');
Route::get('/blocks/saveObservation','BlockController@saveObservation');
Route::get('/blocks/getCaracteristicas','BlockController@getCaracteristicas');	
Route::get('/blocks/getFotos','BlockController@getFotos');
Route::get('/blocks/codify','BlockController@codify');
Route::get('/blocks/print','BlockController@print');
Route::get('/blocks/move_position','BlockController@move_position');
Route::get('/blocks/info_to_compare','BlockController@info_to_compare');
Route::get('/blocks/deleteCodify/{id}','BlockController@deleteCodify');
Route::get('/blocks/getDataChar/','BlockController@getDataChar');
Route::get('/blocks/reorder/{id}','BlockController@reorder');
Route::get('/blocks/discard/','BlockController@discard');
Route::get('/blocks/review/','BlockController@review');
Route::get('/blocks/export/{id}','BlockController@export');
Route::get('/blocks/send_to_blocks','BlockController@send_to_blocks');
Route::get('/blocks/trash','BlockController@trash');
Route::get('/blocks/show_trash/{id}','BlockController@show_trash');
Route::get('/blocks/mark_offline/','BlockController@mark_offline');
Route::resource('blocks', 'BlockController');

Route::get('/mapouts/generateCodify/{id}','MapoutController@generateCodify');
Route::get('/mapouts/deleteCodify/{id}','MapoutController@deleteCodify');
Route::post('/mapouts/updatePosition', 'MapoutController@updatePosition')->name('mapouts.updatePosition');
Route::post('/mapouts/addPositions', 'MapoutController@addPositions')->name('mapouts.addPositions');
Route::resource('mapouts', 'MapoutController');
Route::resource('crossings', 'CrossingController');
Route::resource('features', 'FeatureController');

Route::get("farmers/provinces/", "FarmersController@getProvinces");
Route::get("farmers/communities/", "FarmersController@getCommunities");
Route::get("farmers/lands/", "FarmersController@getLands");

Route::resource('farmers', 'FarmersController');
Route::resource('companies', 'CompanyController');
Route::resource('lands', 'LandController');
Route::resource('traceability', 'TraceabilityController');
Route::get("royalties/create/{farmer_id}", "RoyaltiesController@create");

Route::resource('royalties', 'RoyaltiesController');

Route::get('/results/getData/','ResultsController@getData');
Route::get('/results/crossings/','ResultsController@crossings');
Route::get('/results/fries/','ResultsController@fries');
Route::get('/results/searchCrossings/','CrossingController@searchCrossings');
Route::get('/results/getVaritiesFromBlock/','ResultsController@getVaritiesFromBlock');
Route::get('/results/getChildrensFromVarity/','ResultsController@getChildrensFromVarity');
Route::get('/results/getCaracteristicas/','ResultsController@getCaracteristicas');
Route::get('/results/modCaracteristicas','ResultsController@modCaracteristicas');
Route::any('/fries/save/','BlockController@saveDataFries');			
Route::get('/fries/getData/','BlockController@getDataFries');
Route::any('/fries/updateFries/','BlockController@updateDataFries');			

Route::get('/results/preview_report/','ResultsController@preview_report');
Route::get('/results/load_preview/','ResultsController@load_preview');
Route::any('/results/report/','ResultsController@report');
Route::get('/results/getVarities/','ResultsController@varities');
Route::get('/results/info_to_compare/','ResultsController@info_to_compare');
Route::get('/results/getBlocksByYear/','ResultsController@getBlocksByYear');
Route::get('/results/getVarityByname/','ResultsController@getVarityByname');
Route::get('/results/getVarityBynameInfo/','ResultsController@getVarityBynameInfo');
Route::get('/results/getDataFeature/','ResultsController@getDataFeature');
Route::get('/results/stadistics/','ResultsController@stadistics');

Route::resource('results', 'ResultsController');

Route::resource('std_market', 'StdMarketController');


Route::DELETE('/greenhouse/destroy_greenhouse', 'GreenHouseController@destroy_greenhouse')->name('greenhouse.destroy_greenhouse');
Route::PATCH('/greenhouse/update_greenhouse', 'GreenHouseController@update_greenhouse')->name('greenhouse.update_greenhouse');
Route::get('/greenhouse/asociate_crossing/{id}','GreenHouseController@asociate_crossing')->name('greenhouse.asociate_crossing');
Route::get('/greenhouse/crossings_add/','GreenHouseController@crossings_add');
Route::get('/greenhouse/crossings_added/{id}','GreenHouseController@crossings_added');
Route::post('/greenhouse/store_crossings', 'GreenHouseController@store_crossings');
Route::post('/greenhouse/delete_crossings', 'GreenHouseController@delete_crossings');


Route::get('/greenhouse/generateCodify/{id}','GreenHouseController@generateCodify');
Route::get('/greenhouse/show_mobile/{id}','GreenHouseController@show_mobile');
Route::get('/greenhouse/crossings_ok/{id}','GreenHouseController@crossings_ok');
Route::get('/greenhouse/crossings_list/{id}','GreenHouseController@crossings_list');
Route::get('/greenhouse/show_mobile/{id}','GreenHouseController@show_mobile');
Route::get('/public/draw_greenhouse/{id}','GreenHouseController@draw_greenhouse');
Route::get('draw_greenhouse/{id}','GreenHouseController@draw_greenhouse');
Route::get('/greenhouse/deleteCodify/{id}','GreenHouseController@deleteCodify');
Route::post('/greenhouse/updatePosition', 'GreenHouseController@updatePosition')->name('greenhouse.updatePosition');
Route::post('/greenhouse/addPositions', 'GreenHouseController@addPositions')->name('greenhouse.addPositions');
Route::get('/greenhouse/switch/{varity_id}/{father_id}/{mother_id}','GreenHouseController@switchFathers');
Route::get('/greenhouse/polen/{father_id}/{mother_id}/{status}','GreenHouseController@savePolen');
Route::get('/greenhouse/berries/{id}/{nro_berries}','GreenHouseController@save_berries');
Route::get('/greenhouse/glasses/{id}/{nro_glases}','GreenHouseController@save_glasses');
Route::get('/greenhouse/get_data_chart','GreenHouseController@get_data_chart');
Route::resource('greenhouse', 'GreenHouseController');

Route::get('/relative_yield/calc','RelativeYieldController@calc');

Route::resource('relative_yield', 'RelativeYieldController');

Route::get('/users/logins', 'UserController@logins');
Route::resource('users', 'UserController');

resources/views/crossings/zona/characteristics.blade.php
<form id="saveCharacteristics" action=/crossings/saveCharacteristics method="POST">
	<input type="hidden" name="zonaltrial_id" value="<?= $zonaltrial->id;?>">
	<input type="hidden" name="_token" value="{{ csrf_token() }}">
	<table class="table">
		<thead>
			<tr>
				<th></th>
				<th width="80px">Year 0</th>
				<th width="80px">Year 1</th>
				<th width="80px">Year 2</th>
				<th width="80px">Year 3</th>
				<th width="80px">Year 4</th>
			</tr>
		</thead>
		<tbody>
			@foreach($typesfeatures as $t)
				<tr>
					<td colspan="6"><b>{{ $t->name }}</b></td>
				</tr>
				@foreach($t->features as $f)
					<tr>
						<td>

								{{ $f->name }} 

							<span style="float:right" class="m-badge m-badge--info m-badge--wide">
								@if($f->type == 1)
									Qualification
								@elseif($f->type == 2)
									Yes/No
								@elseif($f->type == 3)
									Value
								@elseif($f->type == 4)
									Text
								@elseif($f->type == 5)
									Matrix
								@endif
							</span>
						</td>
						<td>
							@if (\strpos($f->year, '0') !== false OR \strpos($f->year, '0') !== false)
								<input type="hidden" name="feature[0][<?= $f->id;?>][feature_id]" value="<?= $f->id;?>">
								<input <?= ($f->type == 1)? 'maxlength="1"':'';?> type="text" class="fullsize" name="feature[0][<?= $f->id;?>][value]" value="<?= $f->valor0;?>">
							@endif
						</td>
						<td>
							@if (\strpos($f->year, '0') !== false OR \strpos($f->year, '1') !== false)
								<input type="hidden" name="feature[1][<?= $f->id;?>][feature_id]" value="<?= $f->id;?>">
								<input <?= ($f->type == 1)? 'maxlength="1"':'';?> type="text" class="fullsize" name="feature[1][<?= $f->id;?>][value]" value="<?= $f->valor1;?>">
							@endif
						</td>
						<td>
							@if (\strpos($f->year, '0') !== false OR \strpos($f->year, '2') !== false)
								<input type="hidden" name="feature[2][<?= $f->id;?>][feature_id]" value="<?= $f->id;?>">
								<input <?= ($f->type == 1)? 'maxlength="1"':'';?> type="text" class="fullsize" name="feature[2][<?= $f->id;?>][value]" value="<?= $f->valor2;?>">
							@endif
						</td>
						<td>
							@if (\strpos($f->year, '0') !== false OR \strpos($f->year, '3') !== false)
								<input type="hidden" name="feature[3][<?= $f->id;?>][feature_id]" value="<?= $f->id;?>">
								<input <?= ($f->type == 1)? 'maxlength="1"':'';?> type="text" class="fullsize" name="feature[3][<?= $f->id;?>][value]" value="<?= $f->valor3;?>">
							@endif
						</td>
						<td>
							@if (\strpos($f->year, '0') !== false OR \strpos($f->year, '4') !== false)
								<input type="hidden" name="feature[4][<?= $f->id;?>][feature_id]" value="<?= $f->id;?>">
								<input <?= ($f->type == 1)? 'maxlength="1"':'';?> type="text" class="fullsize" name="feature[4][<?= $f->id;?>][value]" value="<?= $f->valor4;?>">
							@endif
						</td>
					</tr>
				@endforeach
			@endforeach
		</tbody>
	</table>
	<div class="row">
		<div class="col-lg-12">
			<button type="submit" class="btn btn-success" style="float:right"><i class="fa fa-save"></i> Save Characteristics</button>
		</div>
	</div>
</form>

resources/views/crossings/zona/create.blade.php
@extends('layouts.app')

@section('content')

<div class="m-portlet m-portlet--head-solid-bg m-portlet--rounded">
    <div class="m-portlet__head">
        <div class="m-portlet__head-caption">
            <div class="m-portlet__head-title">
                <h3 class="m-portlet__head-text">
                    Add Trial Zone
                </h3>
            </div>          
        </div>
    </div>
    {!! Form::open(array('class' => 'm-form','route' => 'crossings.zonacreate','method'=>'POST','id' => 'FormCreate')) !!}
        <input type="hidden" name="user_id" value="<?= Auth::user()->id;?>">
        <div class="m-portlet__body">   
            <div class="m-form__section m-form__section--first">        
                @include('crossings.zona.form')
            </div>
            <button type="submit" class="btn btn-primary">Create Trial</button>
        </div>

    {!! Form::close() !!}
</div>

<script>
    $(document).ready(function() {
        $("#FormCreate").validate()
	});
</script>


@endsection

resources/views/crossings/zona/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="m-portlet m-portlet--head-solid-bg m-portlet--rounded">
    <div class="m-portlet__head">
        <div class="m-portlet__head-caption">
            <div class="m-portlet__head-title">
                <span class="m-portlet__head-icon">
                    <i class="flaticon-calendar"></i>
                </span>
                <h3 class="m-portlet__head-text">
                    Trial Zone #{{ $zonaltrial->id }}
                </h3>
            </div>          
        </div>
        <div class="m-portlet__head-tools">
            <ul class="m-portlet__nav">
                <li class="m-portlet__nav-item">
                    <a href="{{ route('varities.index') }}" class="m-portlet__nav-link btn btn-outline-primary m-btn m-btn--outline-2x ">
                        Back
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="m-portlet__body">
        @include('crossings.zona.characteristics',['zonaltrial' => $zonaltrial])
    </div>
</div>
@endsection

resources/views/crossings/zona/form.blade.php
<div id="content-cruce">
    <div class="row">
        <div class="col-xs-6 col-sm-6 col-md-6">
            <div class="form-group">
                <strong>Title:</strong>
                {!! Form::text('title', null, array('placeholder' => 'Enter Title','class' => 'form-control  required')) !!}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-3">
            <div class="form-group">
                <strong>Crossing</strong>
                {!! Form::select('varity_id', $crossings,$id,['class' => 'form-control required','placeholder' => 'Select Variety']); !!}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-3">
            <div class="form-group">
                <strong>Community</strong>
                {!! Form::select('community_id', $communities,null,['class' => 'form-control required','placeholder' => 'Select Community']); !!}
            </div>
        </div>
    </div>
    <div class="form-group">
        <strong>Review</strong>
        {!! Form::textarea('review',null,['class' => 'form-control required','placeholder' => 'Write Review']); !!}
    </div>
</div>
<!--
<div class="row">
    
</div> 
-->

<script>
    $(document).ready(function(){
        $("input[name=cruce]").click(function(){
            if ($("input[name=cruce][value=1]").is(":checked")) {
                $("#content-cruce").show()
            }else{
                 $("#content-cruce").hide()
            }
        })
    })
</script>

resources/views/crossings/zona/list.blade.php
@extends('layouts.app')
@section('content')
<div class="m-portlet m-portlet--head-solid-bg m-portlet--rounded">
    <div class="m-portlet__head">
        <div class="m-portlet__head-caption">
            <div class="m-portlet__head-title">
                <span class="m-portlet__head-icon">
                    <i class="flaticon-calendar"></i>
                </span>
                <h3 class="m-portlet__head-text">
                    Crosses
                </h3>
            </div>          
        </div>
    </div>
    <div class="m-portlet__body">
        <ul class="nav nav-tabs nav-fill" role="tablist">
            <li class="nav-item">
                <a class="nav-link active show" data-toggle="tab" href="#listado_cruces">List of Crosses</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#listado_f1">Zone Trials</a>
            </li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active show" id="listado_cruces" role="tabpanel">
                 <table class="table table-striped- table-bordered table-hover table-checkable datatables_p">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Season</th>
                            <th>Mother</th>
                            <th>Father</th>
                            <th>Stage</th>
                            <th>Condition</th>
                            <th>Created By</th>
                            <th style="width:350px"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @if(!empty($crossings))
                            @foreach($crossings as $record)
                                <tr>
                                    <td>{{ $record->id }}</td>
                                    <td>T{{ $record->year }}-{{ $record->year+1 }}</td>
                                    <td><b><a href="/varity/{{ $record->mother->id }}"><?= ($record->mother->crossing == 1)? $record->mother->code:$record->mother->name;?></a></b></td>
                                    <td><b><a href="/varity/{{ $record->father->id }}"><?= ($record->father->crossing == 1)? $record->father->code:$record->father->name;?></a></b></td>
                                    <td>
                                        <center>
                                            <span class="m-badge m-badge--warning m-badge--wide">Year {{ date('Y')-$record->year }}</span>
                                        </center>
                                    </td>
                                    <td>
                                        <center>
                                            @if($record->typecrossing == 1)
                                                <span class="m-badge m-badge--info m-badge--wide">To be encoded</span>
                                            @else
                                                <span class="m-badge m-badge--success m-badge--wide">Encoded</span>
                                            @endif
                                        </center>
                                    </td>
                                    <td>{{ $record->user->name }}</td>
                                    <td>
                                        <center>
                                            <a  href="/crossings/zonacreate/{{ $record->id }}" class="btn btn-outline-info btn-sm">Create Trial Zone</a>
                                        </center>
                                    </td>
                                </tr>
                            @endforeach
                        @endif
                    </tbody>
                </table>
            </div>
            <div class="tab-pane" id="listado_f1" role="tabpanel">
                <table class="table table-striped- table-bordered table-hover table-checkable datatables_p">
                    <thead>
                        <tr>
                            <th>Correlation</th>
                            <th>Title</th>
                            <th>Mother</th>
                            <th>Father</th>
                            <th>Community</th>
                            <th ></th>
                        </tr>
                    </thead>
                    <tbody>
                        @if(!empty($zonal))
                            @foreach($zonal as $z)
                                <tr>
                                    <td><b>{{ $z->id }}</b></td>
                                    <td>{{ $z->title }}</td>
                                    <td><b><a href="/varity/{{ $record->mother->id }}"><?= ($record->mother->crossing == 1)? $record->mother->code:$record->mother->name;?></a></b></td>
                                    <td><b><a href="/varity/{{ $record->father->id }}"><?= ($record->father->crossing == 1)? $record->father->code:$record->father->name;?></a></b></td>
                                    <td>{{ $z->community->name }}</td>
                                    <td>
                                        <center>
                                            <a class="btn btn-outline-warning btn-sm" href="{{ route('crossings.show',$z->varity_id) }}">See Original Crossing</a>
                                            <a class="btn btn-outline-info btn-sm" href="{{ route('crossings.zonashow',$z->id) }}">See Trial</a>
                                            <a class="btn btn-outline-success btn-sm" href="{{ route('crossings.zonaedit',$z->id) }}">Modify Characteristics</a>
                                        </center>
                                    </td>
                                </tr>
                            @endforeach
                        @endif
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script>
    $(window).load(function(){
        // Disable search and ordering by default
        $.extend( $.fn.dataTable.defaults, {
            "searching": false
        } );
        
    })
</script>
@endsection

resources/views/crossings/zona/show.blade.php
@extends('layouts.app')
@section('content')
<div class="m-portlet m-portlet--head-solid-bg m-portlet--rounded">
    <div class="m-portlet__head">
        <div class="m-portlet__head-caption">
            <div class="m-portlet__head-title">
                <span class="m-portlet__head-icon">
                    <i class="flaticon-calendar"></i>
                </span>
                <h3 class="m-portlet__head-text">
                    Trial Zone #{{ $zonaltrial->id }}
                </h3>
            </div>          
        </div>
        <div class="m-portlet__head-tools">
            <ul class="m-portlet__nav">
                <li class="m-portlet__nav-item">
                    <a href="{{ route('varities.index') }}" class="m-portlet__nav-link btn btn-outline-primary m-btn m-btn--outline-2x ">
                        Back
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="m-portlet__body">
        <div class="row">
            <div class="col-lg-6">
                <fieldset>
                    <legend>Original Crossing Summary</legend>
                    <table class="table">
                        <thead>
                            <tr>
                                <th></th>
                                <th>AVG</th>
                                <th>No.</th>
                                <th>STD</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($typesfeatures as $t)
                                <tr>
                                    <td colspan="6"><b>{{ $t->name }}</b></td>
                                </tr>
                                @foreach($t->features as $f)
                                    <?php $avg_count = 0;?>
                                    <?php if($f->crucevalor0 != "") $avg_count++;?>
                                    <?php if($f->crucevalor1 != "") $avg_count++;?>
                                    <?php if($f->crucevalor2 != "") $avg_count++;?>
                                    <?php if($f->crucevalor3 != "") $avg_count++;?>
                                    <?php if($f->crucevalor4 != "") $avg_count++;?>
                                    <?php $avg = $f->crucevalor0 + $f->crucevalor1 + $f->crucevalor2 + $f->crucevalor3 + $f->crucevalor4;?>
                                    <tr>
                                        <td>

                                                {{ $f->name }} 
                                 
                                        </td>
                                        <td>
                                            @if($avg != "")
                                                {{ $avg/$avg_count }}
                                            @else
                                                0
                                            @endif
                                        </td>
                                        <td>
                                            @if($avg != "")
                                                {{ $avg/$avg_count }}
                                            @else
                                                0
                                            @endif
                                        </td>
                                        <td>
                                            @if($avg != "")
                                                {{ $avg/$avg_count }}
                                            @else
                                                0
                                            @endif
                                        </td>
                                    </tr>
                                @endforeach
                            @endforeach
                        </tbody>
                    </table>
                </fieldset>
            </div>
            <div class="col-lg-6">
                <fieldset>
                    <legend>Summary of Trials in Zone {{ $zonaltrial->community->name }}</legend>
                    <table class="table">
                        <thead>
                            <tr>
                                <th></th>
                                <th>AVG</th>
                                <th>No.</th>
                                <th>STD</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($typesfeatures as $t)
                                <tr>
                                    <td colspan="6"><b>{{ $t->name }}</b></td>
                                </tr>
                                @foreach($t->features as $f)
                                    <?php $avg_count = 0;?>
                                    <?php if($f->valor0 != "") $avg_count++;?>
                                    <?php if($f->valor1 != "") $avg_count++;?>
                                    <?php if($f->valor2 != "") $avg_count++;?>
                                    <?php if($f->valor3 != "") $avg_count++;?>
                                    <?php if($f->valor4 != "") $avg_count++;?>
                                    <?php $avg = $f->valor0 + $f->valor1 + $f->valor2 + $f->valor3 + $f->valor4;?>
                                    <tr>
                                        <td>
     
                                                {{ $f->name }} 
                                   
                                        </td>
                                        <td>
                                            @if($avg != "")
                                                {{ $avg/$avg_count }}
                                            @else
                                                0
                                            @endif
                                        </td>
                                        <td>
                                            @if($avg != "")
                                                {{ $avg/$avg_count }}
                                            @else
                                                0
                                            @endif
                                        </td>
                                        <td>
                                            @if($avg != "")
                                                {{ $avg/$avg_count }}
                                            @else
                                                0
                                            @endif
                                        </td>
                                    </tr>
                                @endforeach
                            @endforeach
                        </tbody>
                    </table>
                </fieldset>
            </div>
        </div>
    </div>
</div>
@endsection