routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Models\Feature;

Route::get('/', 'HomeController@index');
Route::get('/import', 'HomeController@import');
Route::post('/import', 'HomeController@importExcel');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/features/add-value', function () {
	return View('features._add-value',['id' => $_GET['id']]);
});

Route::get('/features/get-values', function () {
	$feature = Feature::find($_GET['id']);
	return View('features._get-values',['feature' => $feature]);
});
Route::get('/varities/exporData', 'VarityController@check_db');
Route::get('/varities/searchHome', 'VarityController@searchHome');
Route::get('/varities/searchHomeCrossing', 'VarityController@searchHomeCrossing');
Route::get('/varities/addValues', 'VarityController@addValues');
Route::get('/varities/addFeature', 'VarityController@addFeature');
Route::get('/blocks/addFeature', 'BlockController@addFeature');
Route::post('/varities/saveCharacteristics', 'VarityController@saveCharacteristics');
Route::post('/varities/uploadPhoto', 'VarityController@uploadPhoto');
Route::get('/varities/ancesters/{id}/{maxlevel}/{level}', 'VarityController@ancesters');
Route::put('/varities/financial/{varity}', 'VarityController@financialInfo')->name('varities.financialInfo');
Route::resource('varities', 'VarityController');


Route::get('/crossings/zonashow/{id?}', 'CrossingController@zonashow')->name('crossings.zonashow');
Route::get('/crossings/zonaedit/{id?}', 'CrossingController@zonaedit')->name('crossings.zonaedit');
Route::get('/crossings/zonacreate/{id?}', 'CrossingController@zonacreate')->name('crossings.zonacreate');
Route::post('/crossings/zonacreate', 'CrossingController@zonastore')->name('crossings.zonacreate');
Route::get('/crossings/mapout', 'CrossingController@mapout');
Route::get('/crossings/zona', 'CrossingController@zona');
Route::get('/crossings/saveObservations', 'CrossingController@saveObservations');
Route::post('/crossings/uploadPhoto', 'CrossingController@uploadPhoto');
Route::get('/crossings/deleteCodify', 'CrossingController@deleteCodify');
Route::get('/crossings/generateCodify', 'CrossingController@generateCodify');
Route::get('/crossings/codify/{id}', 'CrossingController@codify');
Route::get('/crossings/finishCodify/{id}', 'CrossingController@finishCodify');
Route::get('/crossings/codedJSON/', 'CrossingController@codedJSON');
Route::get('/crossings/items/', 'CrossingController@items');
Route::post('/crossings/saveCodify/', 'CrossingController@saveCodify');
Route::post('/crossings/saveCharacteristics', 'CrossingController@saveCharacteristics');
Route::get('/crossings/check_ancester/', 'CrossingController@check_ancester');


Route::post('/blocks/saveShowFarms','BlockController@saveShowFarms');
Route::get('/blocks/modCaracteristicas','BlockController@modCaracteristicas');
Route::get('/blocks/saveObservation','BlockController@saveObservation');
Route::get('/blocks/getCaracteristicas','BlockController@getCaracteristicas');	
Route::get('/blocks/getFotos','BlockController@getFotos');
Route::get('/blocks/codify','BlockController@codify');
Route::get('/blocks/print','BlockController@print');
Route::get('/blocks/move_position','BlockController@move_position');
Route::get('/blocks/info_to_compare','BlockController@info_to_compare');
Route::get('/blocks/deleteCodify/{id}','BlockController@deleteCodify');
Route::get('/blocks/getDataChar/','BlockController@getDataChar');
Route::get('/blocks/reorder/{id}','BlockController@reorder');
Route::get('/blocks/discard/','BlockController@discard');
Route::get('/blocks/review/','BlockController@review');
Route::get('/blocks/export/{id}','BlockController@export');
Route::get('/blocks/send_to_blocks','BlockController@send_to_blocks');
Route::get('/blocks/trash','BlockController@trash');
Route::get('/blocks/show_trash/{id}','BlockController@show_trash');
Route::get('/blocks/mark_offline/','BlockController@mark_offline');
Route::resource('blocks', 'BlockController');

Route::get('/mapouts/generateCodify/{id}','MapoutController@generateCodify');
Route::get('/mapouts/deleteCodify/{id}','MapoutController@deleteCodify');
Route::post('/mapouts/updatePosition', 'MapoutController@updatePosition')->name('mapouts.updatePosition');
Route::post('/mapouts/addPositions', 'MapoutController@addPositions')->name('mapouts.addPositions');
Route::resource('mapouts', 'MapoutController');
Route::resource('crossings', 'CrossingController');
Route::resource('features', 'FeatureController');

Route::get("farmers/provinces/", "FarmersController@getProvinces");
Route::get("farmers/communities/", "FarmersController@getCommunities");
Route::get("farmers/lands/", "FarmersController@getLands");

Route::resource('farmers', 'FarmersController');
Route::resource('companies', 'CompanyController');
Route::resource('lands', 'LandController');
Route::resource('traceability', 'TraceabilityController');
Route::get("royalties/create/{farmer_id}", "RoyaltiesController@create");

Route::resource('royalties', 'RoyaltiesController');

Route::get('/results/getData/','ResultsController@getData');
Route::get('/results/crossings/','ResultsController@crossings');
Route::get('/results/fries/','ResultsController@fries');
Route::get('/results/searchCrossings/','CrossingController@searchCrossings');
Route::get('/results/getVaritiesFromBlock/','ResultsController@getVaritiesFromBlock');
Route::get('/results/getChildrensFromVarity/','ResultsController@getChildrensFromVarity');
Route::get('/results/getCaracteristicas/','ResultsController@getCaracteristicas');
Route::get('/results/modCaracteristicas','ResultsController@modCaracteristicas');
Route::any('/fries/save/','BlockController@saveDataFries');			
Route::get('/fries/getData/','BlockController@getDataFries');
Route::any('/fries/updateFries/','BlockController@updateDataFries');			

Route::get('/results/preview_report/','ResultsController@preview_report');
Route::get('/results/load_preview/','ResultsController@load_preview');
Route::any('/results/report/','ResultsController@report');
Route::get('/results/getVarities/','ResultsController@varities');
Route::get('/results/info_to_compare/','ResultsController@info_to_compare');
Route::get('/results/getBlocksByYear/','ResultsController@getBlocksByYear');
Route::get('/results/getVarityByname/','ResultsController@getVarityByname');
Route::get('/results/getVarityBynameInfo/','ResultsController@getVarityBynameInfo');
Route::get('/results/getDataFeature/','ResultsController@getDataFeature');
Route::get('/results/stadistics/','ResultsController@stadistics');

Route::resource('results', 'ResultsController');

Route::resource('std_market', 'StdMarketController');


Route::DELETE('/greenhouse/destroy_greenhouse', 'GreenHouseController@destroy_greenhouse')->name('greenhouse.destroy_greenhouse');
Route::PATCH('/greenhouse/update_greenhouse', 'GreenHouseController@update_greenhouse')->name('greenhouse.update_greenhouse');
Route::get('/greenhouse/asociate_crossing/{id}','GreenHouseController@asociate_crossing')->name('greenhouse.asociate_crossing');
Route::get('/greenhouse/crossings_add/','GreenHouseController@crossings_add');
Route::get('/greenhouse/crossings_added/{id}','GreenHouseController@crossings_added');
Route::post('/greenhouse/store_crossings', 'GreenHouseController@store_crossings');
Route::post('/greenhouse/delete_crossings', 'GreenHouseController@delete_crossings');


Route::get('/greenhouse/generateCodify/{id}','GreenHouseController@generateCodify');
Route::get('/greenhouse/show_mobile/{id}','GreenHouseController@show_mobile');
Route::get('/greenhouse/crossings_ok/{id}','GreenHouseController@crossings_ok');
Route::get('/greenhouse/crossings_list/{id}','GreenHouseController@crossings_list');
Route::get('/greenhouse/show_mobile/{id}','GreenHouseController@show_mobile');
Route::get('/public/draw_greenhouse/{id}','GreenHouseController@draw_greenhouse');
Route::get('draw_greenhouse/{id}','GreenHouseController@draw_greenhouse');
Route::get('/greenhouse/deleteCodify/{id}','GreenHouseController@deleteCodify');
Route::post('/greenhouse/updatePosition', 'GreenHouseController@updatePosition')->name('greenhouse.updatePosition');
Route::post('/greenhouse/addPositions', 'GreenHouseController@addPositions')->name('greenhouse.addPositions');
Route::get('/greenhouse/switch/{varity_id}/{father_id}/{mother_id}','GreenHouseController@switchFathers');
Route::get('/greenhouse/polen/{father_id}/{mother_id}/{status}','GreenHouseController@savePolen');
Route::get('/greenhouse/berries/{id}/{nro_berries}','GreenHouseController@save_berries');
Route::get('/greenhouse/glasses/{id}/{nro_glases}','GreenHouseController@save_glasses');
Route::get('/greenhouse/get_data_chart','GreenHouseController@get_data_chart');
Route::resource('greenhouse', 'GreenHouseController');

Route::get('/relative_yield/calc','RelativeYieldController@calc');

Route::resource('relative_yield', 'RelativeYieldController');

Route::get('/users/logins', 'UserController@logins');
Route::resource('users', 'UserController');

resources/views/crossings/codify.blade.php
@extends('layouts.app')
@section('content')
<div class="m-portlet m-portlet--head-solid-bg m-portlet--rounded">
    <div class="m-portlet__head">
        <div class="m-portlet__head-caption">
            <div class="m-portlet__head-title">
                <span class="m-portlet__head-icon">
                    <i class="flaticon-calendar"></i>
                </span>
                <h3 class="m-portlet__head-text">
                    Encoding (F1)
                </h3>
            </div>          
        </div>
    </div>
    <div class="m-portlet__body">
        <div class="row">
           <div class="col-lg-3">
               Mother: <a href="/varity/{{ $crossing->mother->id }}">{{ $crossing->mother->name }}</a>
           </div>
           <div class="col-lg-3">
               Father: <a href="/varity/{{ $crossing->father->id }}">{{ $crossing->father->name }}</a>
           </div>
           <div class="col-lg-2">
               Crossing Year: {{ $crossing->year }}
           </div>
        </div>
        <br>
        {!! Form::open(array('class' => 'm-form','url' => '/crossings/saveCodify','method'=>'POST','id' => 'FormCodificaciones')) !!}
            <input type="hidden" name="crossing" value="{{ $crossing->id }}">
            <input type="hidden" name="mother_id" value="{{ $crossing->mother->id }}">
            <input type="hidden" name="father_id" value="{{ $crossing->father->id }}">
            <input type="hidden" name="year" value="{{ $crossing->year }}">
            <div class="row">
                <div class="col-lg-2">
                    <div class="form-group">
                        <?= Form::select('market_id', $markets,null,['class' => 'form-control ','placeholder' => '-Select Target-','style' => '']); ?>
                    </div>
                </div>
                <div class="col-lg-2">
                    <div class="form-group">
                        {!! Form::text('count', null, array('placeholder' => 'Enter amount ','class' => 'form-control  ')) !!}
                    </div>
                </div>
                <div class="col-lg-2">
                       <button type="button"  id="add-codify" class="btn btn-success">
                           <i class="fa fa-plus"></i> Add to encoding
                       </button>
                </div>
                <div class="col-lg-2">
                       <button type="button"  id="delete-codify" class="btn btn-danger">
                           <i class="fa fa-trash"></i> Remove encoding
                       </button>
                </div>
            </div>
        <hr>
            <table class="table" id="tabla-codificacion">
                <thead>
                    <tr>
                        <th>Mother</th>
                        <th>Father</th>
                        <th>Target</th>
                        <th>Observation</th>
                        <th width="100px">No. Berries</th>
                        <th>Code</th>
                        <!--<th></th>-->
                    </tr>
                </thead>
            </table>
            <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Guardar codificación</button>
            <button disabled="disabled" style="margin-top: 30px;" id="terminar_codificacion" type="button" class="btn btn-success"><i class="fa fa-arrow-right"></i> Terminar codificación</button>
        </form>
    </div>
</div>




<script>
    $(document).ready(function(){
        $("#FormCodificaciones").validate()

        let year = "<?= $crossing->year;?>"

        var increment = 1;

        $("#FormCodificaciones select[name=market_id]").val("<?= $crossing->market_id;?>")

        var table = $('#tabla-codificacion').DataTable( {
            "order": [[ 1, "desc" ]],
            "paging": false,
            "searching": false,
            processing: true,
            ajax: {
                url: '/crossings/items',
                data: function ( d ) {
                    d.crossing_id = "<?= $crossing->id;?>"
                }
            },
            columns: [
                { 
                    "data": "mother.name",
                    "render": function ( data, type, row ) {
                        $("#terminar_codificacion").removeAttr("disabled")
                        if(row.mother.crossing != 1){
                          return row.mother.name;
                        }else{
                          return row.mother.code;
                        }
                    } 
                },
                { 
                    "data": "father.name",
                    "render": function ( data, type, row ) {
                        if(row.father.crossing != 1){
                          return row.father.name;
                        }else{
                          return row.father.code;
                        }
                    } 
                },
                { 
                    "data": "market.name",
                    "render": function ( data, type, row ) {
                        return row.market.name+'<input type="hidden"  name=data['+(increment)+'][market] class="form-control" value="'+row.market.id+'"/>';
                    } 
                },
                { 
                    "data": "observation",
                    "render": function ( data, type, row ) {
                        if(row.observation == null){
                            row.observation = "";
                        }
                        return '<input type="text"  name=data['+(increment)+'][observation] class="form-control" value="'+row.observation+'"/>';
                    } 
                },
                { 
                    "data": "berries",
                    "render": function ( data, type, row ) {
                        if(row.berries == null){
                            row.berries = "";
                        }
                        return '<input type="text"  name=data['+(increment)+'][berries] class="form-control" value="'+row.berries+'"/>';
                    } 
                },
                { 
                    "data": "code",
                    "render": function ( data, type, row ) {
                        if(row.code == null){
                            row.code = "";
                        }
                        return '<input type="text"  name=data['+(increment++)+'][code] class="form-control" value="'+row.code+'"/>';
                    } 
                }/*,
                { 
                    "data": "code",
                    "render": function ( data, type, row ) {
                        if(row.code == null){
                            row.code = "";
                        }
                        return '<button onclick="delete_row(this)" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i></button>';
                    } 
                },*/
            ]
         } );

        $("#terminar_codificacion").click(function(){
            let id = "<?= $crossing->id;?>"
            Swal({
              title: 'Are you sure you want to finish encoding?',
              text: "",
              type: 'warning',
              showCancelButton: true,
              confirmButtonText: 'Yes, finish',
              cancelButtonText: 'Cancel',
            }).then((result) => {
                if(result.value){
                    location.href = '/crossings/finishCodify/'+id
                }
            })
        })

        $("#delete-codify").click(function(){
            Swal({
              title: 'Are you sure you want to delete encoding?',
              text: "This action is not reversable.",
              type: 'warning',
              showCancelButton: true,
              confirmButtonText: 'Yes, delete',
              cancelButtonText: 'Cancel',
            }).then((result) => {
                if(result.value){
                    $.ajax({
                        url: '/crossings/deleteCodify',
                        type: 'GET',
                        dataType: 'json',
                        data: {crossing: '<?= $crossing->id;?>' },
                    }).done(function(data) {
                        if(data){
                            Swal({
                              title: 'Encoding removed successfully',
                              text: "",
                              type: 'success',
                              showCancelButton: false,
                              showConfirmButton: false,
                            })
                            table.ajax.reload()
                        }else{
                            Swal({
                              title: 'The encoding could not be removed',
                              text: "",
                              type: 'error',
                              showCancelButton: false,
                              showConfirmButton: false,
                            })  
                        }
                    })
                }
            })   
        })


        $("#add-codify").click(function(){
            if($("select[name=market_id] option:selected").val() != "" &&  parseInt($("#FormCodificaciones input[name=count]").val()) > 0){
                $.ajax({
                    url: '/crossings/generateCodify',
                    type: 'GET',
                    dataType: 'json',
                    data: {crossing: '<?= $crossing->id;?>' , market: $("#FormCodificaciones select[name=market_id]").val(), count: $("#FormCodificaciones input[name=count]").val()},
                }).done(function(data) {
                    if(data){
                        table.ajax.reload()
                        Swal({
                          title: 'Encoding was generated',
                          text: "",
                          type: 'success',
                          showCancelButton: false,
                          showConfirmButton: false,
                        })
                    }else{
                        Swal({
                          title: 'Failed to encode',
                          text: "",
                          type: 'error',
                          showCancelButton: false,
                          showConfirmButton: false,
                        })  
                    }
                })
            }else{
                Swal({
                  title: 'Select target and encoding number',
                  text: "",
                  type: 'error',
                  showCancelButton: false,
                  showConfirmButton: false,
                })
            }
        })

        delete_row = function(element){
            table.row( $(element).parents('tr') ).remove().draw();
        }
    })
</script>

@endsection

resources/views/crossings/formcodify.blade.php
<input type="hidden" name="crossing" value="1">
<div id="content-cruce">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-4">
            <div class="form-group">
                <strong>Target Market</strong>
                {!! Form::select('market_id', $markets,null,['class' => 'form-control required','placeholder' => 'Select Market']); !!}
            </div>
        </div>
        <div class="col-xs-6 col-sm-6 col-md-4">
            <div class="form-group">
                <strong>Berries:</strong>
                {!! Form::text('berries', null, array('placeholder' => 'Berry Quantity','class' => 'form-control  required')) !!}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4">
            <div class="form-group">
                <strong>Observation:</strong>
                {!! Form::text('observation', null, array('placeholder' => '','class' => 'form-control  ')) !!}
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function(){
        $("select").select2();
    })
</script>

resources/views/crossings/index.blade.php
@extends('layouts.app')
@section('content')
<style type="text/css">
    .pagination{
        margin-top: -15px!important;
    }
</style>
<div class="m-portlet m-portlet--head-solid-bg m-portlet--rounded">
    <div class="m-portlet__head">
        <div class="m-portlet__head-caption">
            <div class="m-portlet__head-title">
                <span class="m-portlet__head-icon">
                    <i class="flaticon-calendar"></i>
                </span>
                <h3 class="m-portlet__head-text">
                    Cruces
                </h3>
            </div>          
        </div>
        <div class="m-portlet__head-tools">
            <ul class="m-portlet__nav">
                <li class="m-portlet__nav-item">
                    <a href="{{ route('crossings.create') }}" class="m-portlet__nav-link btn btn-outline-primary m-btn m-btn--outline-2x ">
                        Create Crossing
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="m-portlet__body">
        <ul class="nav nav-tabs nav-fill" role="tablist">
            <li class="nav-item">
                <a class="nav-link active show" data-toggle="tab" href="#listado_cruces">List of Crossings</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="tab" href="#listado_f1">List of Encodings (F-1)</a>
            </li>
        </ul>
        <div class="tab-content">
            <div class="tab-pane active show" id="listado_cruces" role="tabpanel">
                 <table class="table table-striped- table-bordered table-hover table-checkable">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Season</th>
                            <th>Mother</th>
                            <th>Father</th>
                            <th>Target Market</th>
                            <th>Stage</th>
                            <th>Condition</th>
                            <th>Created By</th>
                            <th>Date</th>
                            <th style="width:250px"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @if(!empty($crossings))
                            @foreach($crossings as $record)
                                <tr>
                                    <td>{{ $record->id }}</td>
                                    <td>T{{ $record->year }}-{{ $record->year+1 }}</td>
                                    <td>
                                        <b>
                                            <a href="/varities/{{ @$record->mother->id }}">
                                                {{ @$record->motherName() }}
                                            </a>
                                        </b>
                                    </td>
                                    <td>
                                        <b>
                                            <a href="/varities/{{ @$record->father->id }}">
                                                {{ @$record->fatherName() }}
                                            </a>
                                        </b>
                                    </td>
                                    <td>
                                        <b>
                                            @if(!empty($record->marketold_id))
                                                @if($record->marketold_id == $record->market_id)
                                                    {{ @$record->market->name }}
                                                @else
                                                    Original: {{ @$record->marketold->name }}, Modified: {{ @$record->market->name }}
                                                @endif
                                            @else
                                                {{ @$record->market->name }}
                                            @endif
                                        </b>
                                    </td>
                                    <td>
                                        <center>
                                            <span class="m-badge m-badge--warning m-badge--wide">Year {{ date('Y')-$record->year }}</span>
                                        </center>
                                    </td>
                                    <td>
                                        <center>
                                            @if($record->typecrossing == 1)
                                                <span class="m-badge m-badge--info m-badge--wide">To be encoded</span>
                                            @else
                                                <span class="m-badge m-badge--success m-badge--wide">Encoded</span>
                                            @endif
                                        </center>
                                    </td>
                                    <td>{{ @$record->user->name }}</td>
                                    <td>{{ @$record->created_at }}</td>
                                    <td>
                                        <center>
                                            @if($record->typecrossing == 1)
                                                <a class="btn btn-outline-info btn-sm" href="/crossings/codify/{{ $record->id }}">Encoding</a>
                                            @else
                                                <a class="btn btn-outline-info btn-sm" href="{{ route('crossings.show',$record->id) }}">See Info</a>
                                            @endif
                                            <a class="btn btn-outline-success btn-sm" href="{{ route('crossings.edit',$record->id) }}">Edit</a>
                                            <!--{!! Form::open(['method' => 'DELETE','route' => ['crossings.destroy', $record->id],'style'=>'display:inline']) !!}
                                            {!! Form::submit('Eliminar', ['class' => 'btn btn-outline-danger btn-sm btn-delete']) !!}
                                            {!! Form::close() !!}-->
                                        </center>
                                    </td>
                                </tr>
                            @endforeach
                        @endif
                    </tbody>
                </table>
            </div>
            <div class="tab-pane" id="listado_f1" role="tabpanel">
                <table class="table table-striped- table-bordered table-hover table-checkable">
                    <thead>
                        <tr>
                            <th>Code</th>
                            <th>Season</th>
                            <th>Market</th>
                            <th>Berries</th>
                            <th>Mother</th>
                            <th>Father</th>
                            <th>Stage</th>
                            <th style="width:180px"></th>
                        </tr>
                    </thead>
                    <tbody>
                        @if(!empty($coded))
                            @foreach($coded as $c)
                                <tr>
                                    @if(!empty($c->code))
                                        <td><b>{{ $c->code }}</b></td>

                                    @else
                                     <td><b>{{ $c->name }}</b></td>

                                    @endif
                                    <td>T{{ $c->year }}-{{ $c->year+1 }}</td>
                                    <td>
                                        <b>
                                            @if($c->marketold_id == $c->market_id)
                                                {{ @$c->market->name }}
                                            @else
                                                Original: {{ @$c->marketold->name }}, Modified: {{ @$c->market->name }}
                                            @endif
                                        </b>
                                    </td>
                                    <td>{{ $c->berries }}</td>
                                    <td>
                                        <b>
                                            <a href="/varities/{{ @$c->mother->id }}">
                                                {{ @$c->motherName() }}
                                            </a>
                                        </b>
                                    </td>
                                    <td>
                                        <b>
                                            <a href="/varities/{{ @$c->father->id }}">
                                                {{ @$c->fatherName() }}
                                            </a>
                                        </b>
                                    </td>
                                    <td>
                                        <center>
                                            <span class="m-badge m-badge--warning m-badge--wide">Year {{ date('Y')-$c->year }}</span>
                                        </center>
                                    </td>
                                    <td>
                                        <center>
                                            <a class="btn btn-outline-info btn-sm" href="{{ route('crossings.show',$c->id) }}">View</a>
                                            <a class="btn btn-outline-success btn-sm" href="{{ route('crossings.edit',$c->id) }}">Edit</a>
                                        </center>
                                    </td>
                                </tr>
                            @endforeach
                        @endif
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script>
    $(window).load(function(){
         $(".table").DataTable({
          dom: 'Bfrtip',
          buttons: [{
                    extend: 'excel',
                    text: 'Excel',
                    exportOptions: {
                         columns: [ 0,1,2,3,4,5]
                    }
                }]
        })
    })

</script>
@endsection